### ISSUE TITLE
Remove commit enforcement

### ISSUE THREAD

**Issue by stramel** [psyrendust/grunt-eol#3]
Installing the latest version of grunt-eol requires that we conform to the angular-precommit hook. Removing the postinstall npm hook should resolve this.

**Comment by psyrendust** [comment]
@stramel let me know if the latest patch release fixes the issue for you.

**Comment by stramel** [comment]
seems overkill for a commit hook but I will give it a shot

**Comment by stramel** [comment]
```
npm ERR! grunt-eol@1.1.2 postinstall: `if [ -z "$(node ./check-env.js)" ]; then npm run installhook; fi`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grunt-eol@1.1.2 postinstall script 'if [ -z "$(node ./check-env.js)" ]; then npm run installhook; fi'.
```

Running Windows 7 and Node v6.3.0

**Comment by psyrendust** [comment]
I'll check this out after in a bit, sorry for the inconvenience.

Larry
